### ISSUE TITLE
Competition analysis

### ISSUE THREAD

**Issue by danidi-git** [Nadiaki/Sushi-Norregade#32]
Using the list of competition websites on the drive, for each of the restaurant write down:
- running sushi or fresh?
- all you can eat?
- just eat
- trust pilot/trip advisor or similar
- offers
- social media presence
- online booking system
- distance from Sushi Norregade
- what else is special about them?
(and anything else that might be relevant for the research)

Put the data in the spreadsheet on drive:
https://docs.google.com/spreadsheets/d/1h7BczG3l7U4yfU-BpVFpZmqzo6-cbRMQH6mrtc-kBZA/edit

**Comment by danidi-git** [comment]
List done, except for the price comparison. 
Should we do that to confirm if we can compete on price? Thao might be fastest to do so, as she knows prices by heart. :)
I've removed some of the restaurants that were on the list, as they were either very far away or focusing on Japanese food in general and they had very little sushi.

**Comment by thaodo0492** [comment]
you mean the price with the same roll in different restaurant?  but how about the quality and the products they use that affect the price, should we not care at all?
